### ISSUE TITLE
Connecting this header file to my project generates error, saying some things are being redefined

### ISSUE THREAD

**Issue by justinjk007** [adishavit/simple-svg#3]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"class std::basic_string<char,struct std::char_traits,class std::allocator > __cdecl svg::elemStart(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?elemStart@svg@@ya?AV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@aebv23@@z) already defined in run_tests.obj	run_tests	1
```
About 9 of them like this...what do ?

**Comment by justinjk007** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl svg::elemStart(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?elemStart@svg@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV23@@Z) already defined in run_tests.obj	run_tests	1

About 9 of them like this...what do ?

**Comment by adishavit** [comment]
I haven't used this in a long while!
In any case, your have an `already defined` linker error so I suspect you are `#include`ing the file from multiple source files and the offending method (`elemStart()`) is not declared `inline`.
Try making `attribute()`, `elemStart()`, `elemEnd()`, and `emptyElemEnd()` inline functions (they are not methods). 
I think it should fix the problem. 
If it does - great! Please make a pull-request and I'll merge it.

_(I am not the original author - I just cloned/forked it to GitHub a couple of years ago and made a few fixes - contributions welcome!)_

**Comment by justinjk007** [comment]
Thank you very very very much. Doing the above got rid of 4 errors so inlined the other methods as well that fixed the error. I tested it on the main file you are supplying as well. That still works too.. I will make a pull request right away.

**Comment by adishavit** [comment]
Great!
There is no need to `inline` methods defined inside the `class` bodies (they are automatically inlined. 
Only free standing functions (e.g. in the namespace) or method who's body is defined outside the `class` body.
👍

**Comment by adishavit** [comment]
... and that's what you did 👍

**Comment by justinjk007** [comment]
Yeah, I didn't inline any class functions

**Comment by adishavit** [comment]
Merged!

**Comment by justinjk007** [comment]
Thanks
