### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by deduktionstheorem** [adishavit/simple-svg#9]
Hi! Could you please use git tags? That would enable packagers to download a specifically tagged version of the sources; this ensures that the checksum doesn't change. (I see there were some commits but the version didn't chage.)

Right now, I only have the option to download https://github.com/adishavit/simple-svg/archive/refs/heads/master.zip (I assume it will be 1.0.0.zip if you set a tag), but that checksum will change with the next commit.

Thanks!!

**Comment by adishavit** [comment]
Done.
See release [v1.0.1](https://github.com/adishavit/simple-svg/releases/tag/v1.0.1).

**Comment by deduktionstheorem** [comment]
That was fast! Thanks!

**Comment by micwoj92** [comment]
Hi @deduktionstheorem thanks for taking action, a bif of advice for future, from GitHub you can also download zip sources per commit, example https://github.com/adishavit/simple-svg/archive/refs/heads/aab751c7372e463cdfbe2087c79b7531a3c75135.zip
